spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/postgres}
spring.datasource.driverClassName=${DB_DRIVER:org.postgresql.Driver}
spring.datasource.username=${DB_USERNAME:postgres}
<<<<<<< HEAD
spring.datasource.password=${DB_PASSWORD:1111}
=======
spring.datasource.password=${DB_PASSWORD:}
>>>>>>> 524a0e1364287037ac59b4a573e1ba2a6b60e60d
spring.jpa.database-platform=${DB_DIALECT:org.hibernate.dialect.PostgreSQLDialect}
spring.jpa.hibernate.ddl-auto=${DDL_AUTO:update}
spring.h2.console.enabled=false
